### ISSUE TITLE
Instabilité et crash de l'application lors de multiples scans rapides avec la librairie

### ISSUE THREAD

**Issue by abelatar** [enioka-Haute-Couture/enioka_scan#112]
Hello @marcanpilami ,
Lorsque nous exécutons plusieurs scans rapides en succession en utilisant la librairie dans notre application, nous observons une instabilité conduisant à un crash de l'application après une dizaine de scans. voici des traces que j'ai pu récupèrer après l'arrêt de l'application.

```
CameraManagerGlobal           I  Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_ACTIVE for client com.geodis.mobiprep API Level 2
BARCODE                       D  barcode read: JVGTS5437650876115112
CamBarcodeScanVScanner        V  handleScanResult JVGTS5437650876115112 - CODE128
ScannerActivity               D  Received barcode from scanner: JVGTS5437650876115112 - CODE128
ParcelLoadingActivity         I  onData handled in ParcelLoadingActivity
BARCODE                       I  Stopping capture session
BufferQueueProducer           E  [ImageReader-640x480f23m18-21419-54](id:53ab00000036,api:4,p:3866,c:21419) queueBuffer: BufferQueue has been abandoned
Toast                         D  show: caller = com.geodis.mobiprep.MobiprepActivity.showScanFailureMessage:630 
                              I  show: focusDisplayId = 0, isFocusInDesktop = false mCustomDisplayId=-1 isDexDualMode=false
                              I  show: isActivityContext = false
NotificationService           E  Package has already posted 25 toasts. Not showing more. Package=com.geodis.mobiprep
BARCODE                       I  Initializing or reinitializing preview analysis loop
                              D  Capture session creation begins
BufferQueueProducer           E  [ImageReader-640x480f23m18-21419-54](id:53ab00000036,api:4,p:3866,c:21419) queueBuffer: BufferQueue has been abandoned
                              E  [ImageReader-640x480f23m18-21419-54](id:53ab00000036,api:4,p:3866,c:21419) queueBuffer: BufferQueue has been abandoned
AudioTrack                    D  stop(153): called with 4992 frames delivered
BufferQueueProducer           E  [ImageReader-640x480f23m18-21419-54](id:53ab00000036,api:4,p:3866,c:21419) queueBuffer: BufferQueue has been abandoned
                              E  [ImageReader-640x480f23m18-21419-54](id:53ab00000036,api:4,p:3866,c:21419) queueBuffer: BufferQueue has been abandoned
                              E  [ImageReader-640x480f23m18-21419-54](id:53ab00000036,api:4,p:3866,c:21419) queueBuffer: BufferQueue has been abandoned
                              E  [ImageReader-640x480f23m18-21419-54](id:53ab00000036,api:4,p:3866,c:21419) queueBuffer: BufferQueue has been abandoned
                              E  [ImageReader-640x480f23m18-21419-54](id:53ab00000036,api:4,p:3866,c:21419) queueBuffer: BufferQueue has been abandoned
CameraManagerGlobal           I  Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_IDLE for client com.geodis.mobiprep API Level 2
BARCODE                       D  Configuration request sent
geodis.mobipre                W  Long monitor contention with owner main (21419) at void android.hardware.camera2.impl.CameraDeviceImpl.waitUntilIdle()(CameraDeviceImpl.java:1283) waiters=1 in void android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.onResultReceived(android.hardware.camera2.impl.CameraMetadataNative, android.hardware.camera2.impl.CaptureResultExtras, android.hardware.camera2.impl.PhysicalCaptureResultInfo[]) for 360ms
BARCODE                       D  Preview analysis loop start method done
                              I  Capture session is now configured and will start the capture request loop 86274442
                              D  Using metering zone (270,190) (370,290)
                              D  Setting AF mode to 4
BpBinder                      I  onLastStrongRef automatically unlinking death recipients: <uncached descriptor>
BARCODE                       I  Camera repeating capture request was set up 86274442
                              D  Capture session has nothing to process 86274442
                              D  Capture session is getting active 86274442
SurfaceControl                I  nativeRelease nativeObject s[535543398048]
                              I  nativeRelease nativeObject e[535543398048]
                              I  assignNativeObject: nativeObject = 0 Surface(name=null)/@0x1d98e29 / android.view.SurfaceControl.readFromParcel:1117 android.view.IWindowSession$Stub$Proxy.relayout:1820 android.view.ViewRootImpl.relayoutWindow:9005 android.view.ViewRootImpl.performTraversals:3360 android.view.ViewRootImpl.doTraversal:2618 android.view.ViewRootImpl$TraversalRunnable.run:9971 android.view.Choreographer$CallbackRecord.run:1010 android.view.Choreographer.doCallbacks:809 android.view.Choreographer.doFrame:744 android.view.Choreographer$FrameDisplayEventReceiver.run:995 
                              I  nativeRelease nativeObject s[535822190752]
                              I  nativeRelease nativeObject e[535822190752]
                              I  nativeRelease nativeObject s[537417332896]
                              I  nativeRelease nativeObject e[537417332896]
ViewRootImpl@...ingActivity]  I  Relayout returned: old=(0,0,720,1280) new=(0,0,720,1280) req=(720,1280)0 dur=24 res=0x1 s={true 537153421312} ch=false fn=124
SurfaceView                   I  positionLost: rt = android.view.SurfaceControl$Transaction@28174c8 surfaceControl = Surface(name=SurfaceView - com.geodis.mobiprep/com.geodis.mobiprep.ParcelLoadingActivity@8a4a268@0)/@0xd63d961 frame = 124
BARCODE                       I  Capture session has closed 23849232
                              D  Capture session has nothing to process 86274442
SurfaceControl                I  nativeRelease nativeObject s[535570703200]
                              I  nativeRelease nativeObject e[535570703200]
                              I  assignNativeObject: nativeObject = 0 Surface(name=null)/@0x1d98e29 / android.view.SurfaceControl.readFromParcel:1117 android.view.IWindowSession$Stub$Proxy.relayout:1820 android.view.ViewRootImpl.relayoutWindow:9005 android.view.ViewRootImpl.performTraversals:3360 android.view.ViewRootImpl.doTraversal:2618 android.view.ViewRootImpl$TraversalRunnable.run:9971 android.view.Choreographer$CallbackRecord.run:1010 android.view.Choreographer.doCallbacks:809 android.view.Choreographer.doFrame:744 android.view.Choreographer$FrameDisplayEventReceiver.run:995 
                              I  nativeRelease nativeObject s[535570703296]
                              I  nativeRelease nativeObject e[535570703296]
                              I  nativeRelease nativeObject s[535543398048]
                              I  nativeRelease nativeObject e[535543398048]
ViewRootImpl@...ingActivity]  I  Relayout returned: old=(0,0,720,1280) new=(0,0,720,1280) req=(720,1280)0 dur=21 res=0x1 s={true 537153421312} ch=false fn=126
SurfaceView                   I  setParentSpaceRectangle: useBLAST = false position = Rect(0, 494 - 720, 1280) frameNumber = 126 t = android.view.SurfaceControl$Transaction@28174c8
                              I  applySurfaceTransforms: t = android.view.SurfaceControl$Transaction@28174c8 surfaceControl = Surface(name=SurfaceView - com.geodis.mobiprep/com.geodis.mobiprep.ParcelLoadingActivity@8a4a268@0)/@0xd63d961 frame = 126
                              I  applySurfaceTransforms: postScaleX = 1.125 postScaleY = 1.6375
libEGL                        W  EGLNativeWindowType 0x7d10d45010 disconnect failed
ViewRootImpl@f40d15e[Toast]   D  dispatchDetachedFromWindow: reset blurmask
                              I  dispatchDetachedFromWindow
SurfaceControl                I  nativeRelease nativeObject s[535822200064]
                              I  nativeRelease nativeObject e[535822200064]
InputTransport                D  Input channel destroyed: '49abef1', fd=85
ToastPresenter                V  sipHeight = 0
InputTransport                D  Input channel constructed: '777bb1a', fd=85
ViewRootImpl@447b02f[Toast]   I  setView = android.widget.LinearLayout@d8e863c TM=true
CameraManagerGlobal           I  Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_ACTIVE for client com.geodis.mobiprep API Level 2
SurfaceControl                I  assignNativeObject: nativeObject = 0 Surface(name=null)/@0xfd9fc5 / android.view.SurfaceControl.readFromParcel:1117 android.view.IWindowSession$Stub$Proxy.relayout:1820 android.view.ViewRootImpl.relayoutWindow:9005 android.view.ViewRootImpl.performTraversals:3360 android.view.ViewRootImpl.doTraversal:2618 android.view.ViewRootImpl$TraversalRunnable.run:9971 android.view.Choreographer$CallbackRecord.run:1010 android.view.Choreographer.doCallbacks:809 android.view.Choreographer.doFrame:744 android.view.Choreographer$FrameDisplayEventReceiver.run:995 
ViewRootImpl@447b02f[Toast]   I  Relayout returned: old=(0,48,720,1280) new=(63,976,656,1152) req=(593,176)0 dur=28 res=0x7 s={true 537153261568} ch=true fn=-1
                              I  [DP] dp(1) 0 android.view.ViewRootImpl.reportNextDraw:10957 android.view.ViewRootImpl.performTraversals:3845 android.view.ViewRootImpl.doTraversal:2618 
                              I  [DP] pd() Asnyc report
                              I  [DP] pdf(0) 0 android.view.ViewRootImpl.lambda$performDraw$1$ViewRootImpl:4668 android.view.-$$Lambda$ViewRootImpl$DJd0VUYJgsebcnSohO6h8zc_ONI.run:6 android.os.Handler.handleCallback:938 
                              I  [DP] rdf()
BARCODE                       D  FPS: 2.2768383 - Pool size: 8. Current analysis queue depth: 0. Current res: 640*480. Statistics are: {Point(640, 480)=22, Point(352, 288)=5, Point(960, 720)=5, Point(1440, 1080)=10}
                              I  Changing preview resolution from 640*480 to 352*288
                              D  New preview resolution set
                              I  Stopping capture session
BufferQueueProducer           E  [ImageReader-640x480f23m18-21419-55](id:53ab00000037,api:4,p:3866,c:21419) queueBuffer: BufferQueue has been abandoned
BARCODE                       D  barcode read: JVGTS0030170000923190
SurfaceView                   I  surfaceChanged (352,288) 1 #5 com.enioka.scanner.camera.CameraPreviewSurfaceView{8a4a268 V.E...... ......I. 0,0-720,786}
BARCODE                       I  surface changed 86274442
ViewRootImpl@...ingActivity]  I  [DP] dp(1) 1 android.view.SurfaceView.updateSurface:1311 android.view.SurfaceView.setFrame:646 android.view.View.layout:24472 
                              I  [DP] pdf(0) 1 android.view.SurfaceView.notifyDrawFinished:577 android.view.SurfaceView.performDrawFinished:564 android.view.SurfaceView.lambda$TWz4D2u33ZlAmRtgKzbqqDue3iM:0 
                              I  [DP] rdf()
CamBarcodeScanVScanner        V  handleScanResult JVGTS0030170000923190 - CODE128
BARCODE                       I  Initializing or reinitializing preview analysis loop
                              D  Capture session creation begins
BufferQueueProducer           E  [ImageReader-640x480f23m18-21419-55](id:53ab00000037,api:4,p:3866,c:21419) queueBuffer: BufferQueue has been abandoned
AudioTrack                    D  stop(153): called with 4992 frames delivered
BufferQueueProducer           E  [ImageReader-640x480f23m18-21419-55](id:53ab00000037,api:4,p:3866,c:21419) queueBuffer: BufferQueue has been abandoned
                              E  [ImageReader-640x480f23m18-21419-55](id:53ab00000037,api:4,p:3866,c:21419) queueBuffer: BufferQueue has been abandoned
                              E  [ImageReader-640x480f23m18-21419-55](id:53ab00000037,api:4,p:3866,c:21419) queueBuffer: BufferQueue has been abandoned
                              E  [ImageReader-640x480f23m18-21419-55](id:53ab00000037,api:4,p:3866,c:21419) queueBuffer: BufferQueue has been abandoned
                              E  [ImageReader-640x480f23m18-21419-55](id:53ab00000037,api:4,p:3866,c:21419) queueBuffer: BufferQueue has been abandoned
                              E  [ImageReader-640x480f23m18-21419-55](id:53ab00000037,api:4,p:3866,c:21419) queueBuffer: BufferQueue has been abandoned
CameraManagerGlobal           I  Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_IDLE for client com.geodis.mobiprep API Level 2
BARCODE                       D  Configuration request sent
geodis.mobipre                W  Long monitor contention with owner main (21419) at void android.hardware.camera2.impl.CameraDeviceImpl.waitUntilIdle()(CameraDeviceImpl.java:1283) waiters=0 in void android.hardware.camera2.impl.CameraDeviceImpl$4.run() for 408ms
BARCODE                       D  Preview analysis loop start method done
                              I  Capture session is now configured and will start the capture request loop 86274442
geodis.mobipre                W  Long monitor contention with owner main (21419) at void android.hardware.camera2.impl.CameraDeviceImpl.waitUntilIdle()(CameraDeviceImpl.java:1283) waiters=1 in void android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.onResultReceived(android.hardware.camera2.impl.CameraMetadataNative, android.hardware.camera2.impl.CaptureResultExtras, android.hardware.camera2.impl.PhysicalCaptureResultInfo[]) for 407ms
ScannerActivity               D  Received barcode from scanner: JVGTS0030170000923190 - CODE128
ParcelLoadingActivity         I  onData handled in ParcelLoadingActivity
BARCODE                       I  Stopping capture session
Toast                         D  show: caller = com.geodis.mobiprep.MobiprepActivity.showScanFailureMessage:630 
                              I  show: focusDisplayId = 0, isFocusInDesktop = false mCustomDisplayId=-1 isDexDualMode=false
                              I  show: isActivityContext = false
AndroidRuntime                E  FATAL EXCEPTION: CameraBackground
                                 Process: com.geodis.mobiprep, PID: 21419
                                 java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Surface android.media.ImageReader.getSurface()' on a null object reference
                                 	at com.enioka.scanner.camera.CameraBarcodeScanViewV2$3.onConfigured(CameraBarcodeScanViewV2.java:575)
                                 	at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy.lambda$onConfigured$0$CallbackProxies$SessionStateCallbackProxy(CallbackProxies.java:53)
                                 	at android.hardware.camera2.impl.-$$Lambda$CallbackProxies$SessionStateCallbackProxy$soW0qC12Osypoky6AfL3P2-TeDw.run(Unknown Source:4)
                                 	at android.os.Handler.handleCallback(Handler.java:938)
                                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                                 	at android.os.Looper.loop(Looper.java:246)
                                 	at android.os.HandlerThread.run(HandlerThread.java:67)
BARCODE                       I  Initializing or reinitializing preview analysis loop
                              D  Capture session creation begins
Process                       I  Sending signal. PID: 21419 SIG: 9
```

Ou dans un autre cas : 

```
SurfaceView                   I  surfaceChanged (960,720) 1 #5 com.enioka.scanner.camera.CameraPreviewSurfaceView{8a4a268 V.E...... ......I. 0,0-720,786}
BARCODE                       I  surface changed 86274442
ViewRootImpl@...ingActivity]  I  [DP] dp(1) 1 android.view.SurfaceView.updateSurface:1311 android.view.SurfaceView.setFrame:646 android.view.View.layout:24472 
                              I  [DP] pdf(0) 1 android.view.SurfaceView.notifyDrawFinished:577 android.view.SurfaceView.performDrawFinished:564 android.view.SurfaceView.lambda$TWz4D2u33ZlAmRtgKzbqqDue3iM:0 
                              I  [DP] rdf()
BARCODE                       I  Initializing or reinitializing preview analysis loop
                              D  Capture session creation begins
BufferQueueProducer           E  [ImageReader-640x480f23m18-25566-49](id:63de00000031,api:4,p:3866,c:25566) queueBuffer: BufferQueue has been abandoned
                              E  [ImageReader-640x480f23m18-25566-49](id:63de00000031,api:4,p:3866,c:25566) queueBuffer: BufferQueue has been abandoned
                              E  [ImageReader-640x480f23m18-25566-49](id:63de00000031,api:4,p:3866,c:25566) queueBuffer: BufferQueue has been abandoned
                              E  [ImageReader-640x480f23m18-25566-49](id:63de00000031,api:4,p:3866,c:25566) queueBuffer: BufferQueue has been abandoned
                              E  [ImageReader-640x480f23m18-25566-49](id:63de00000031,api:4,p:3866,c:25566) queueBuffer: BufferQueue has been abandoned
                              E  [ImageReader-640x480f23m18-25566-49](id:63de00000031,api:4,p:3866,c:25566) queueBuffer: BufferQueue has been abandoned
                              E  [ImageReader-640x480f23m18-25566-49](id:63de00000031,api:4,p:3866,c:25566) queueBuffer: BufferQueue has been abandoned
                              E  [ImageReader-640x480f23m18-25566-49](id:63de00000031,api:4,p:3866,c:25566) queueBuffer: BufferQueue has been abandoned
CameraManagerGlobal           I  Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_IDLE for client com.geodis.mobiprep API Level 2
BARCODE                       D  Configuration request sent
geodis.mobipre                W  Long monitor contention with owner main (25566) at void android.hardware.camera2.impl.CameraDeviceImpl.waitUntilIdle()(CameraDeviceImpl.java:1283) waiters=0 in void android.hardware.camera2.impl.CameraDeviceImpl$4.run() for 437ms
BARCODE                       D  Preview analysis loop start method done
                              I  Capture session is now configured and will start the capture request loop 86274442
geodis.mobipre                W  Long monitor contention with owner main (25566) at void android.hardware.camera2.impl.CameraDeviceImpl.waitUntilIdle()(CameraDeviceImpl.java:1283) waiters=1 in void android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.onResultReceived(android.hardware.camera2.impl.CameraMetadataNative, android.hardware.camera2.impl.CaptureResultExtras, android.hardware.camera2.impl.PhysicalCaptureResultInfo[]) for 436ms
BARCODE                       D  Using metering zone (430,310) (530,410)
                              D  Setting AF mode to 4
BpBinder                      I  onLastStrongRef automatically unlinking death recipients: <uncached descriptor>
BARCODE                       I  Camera repeating capture request was set up 86274442
                              D  Capture session has nothing to process 86274442
                              D  Capture session is getting active 86274442
                              I  Capture session has closed 251608643
                              D  Capture session has nothing to process 86274442
CameraManagerGlobal           I  Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_ACTIVE for client com.geodis.mobiprep API Level 2
BARCODE                       I  Discarding old buffer of length 307200 (requested 691200) 0
                              D  Creating new buffer (MB) 0 count is 1
                              I  Discarding old cropped buffer of length 38115 (requested 85396)
                              I  Discarding old cropped buffer of length 38115 (requested 85396)
                              D  Creating new cropped buffer (MB) 0
                              D  FPS: 7.4882894 - Pool size: 8. Current analysis queue depth: 0. Current res: 960*720. Statistics are: {Point(640, 480)=53, Point(352, 288)=10}
                              D  Creating new cropped buffer (MB) 0
                              D  barcode read: JVGTS0030170000923190
CamBarcodeScanVScanner        V  handleScanResult JVGTS0030170000923190 - CODE128
ScannerActivity               D  Received barcode from scanner: JVGTS0030170000923190 - CODE128
ParcelLoadingActivity         I  onData handled in ParcelLoadingActivity
BARCODE                       I  Stopping capture session
AndroidRuntime                D  Shutting down VM
                              E  FATAL EXCEPTION: main
                                 Process: com.geodis.mobiprep, PID: 25566
                                 java.lang.IllegalArgumentException: This image was not produced by this ImageReader
                                 	at android.media.ImageReader.releaseImage(ImageReader.java:549)
                                 	at android.media.ImageReader.access$700(ImageReader.java:60)
                                 	at android.media.ImageReader$SurfaceImage.close(ImageReader.java:824)
                                 	at android.media.ImageReader.close(ImageReader.java:638)
                                 	at com.enioka.scanner.camera.CameraBarcodeScanViewV2.pauseCamera(CameraBarcodeScanViewV2.java:343)
                                 	at com.enioka.scanner.camera.CameraBarcodeScanView.pauseCamera(CameraBarcodeScanView.java:174)
                                 	at com.enioka.scanner.sdk.camera.CameraBarcodeScanViewScanner.pause(CameraBarcodeScanViewScanner.java:89)
                                 	at com.enioka.scanner.api.Scanner.pause(Scanner.java:102)
                                 	at com.geodis.mobiprep.ParcelLoadingActivity.onParcelScan(ParcelLoadingActivity.java:281)
                                 	at com.geodis.mobiprep.ParcelLoadingActivity.onData(ParcelLoadingActivity.java:390)
                                 	at com.enioka.scanner.activities.ScannerCompatActivity.lambda$actuallyOpenCamera$0$ScannerCompatActivity(ScannerCompatActivity.java:402)
                                 	at com.enioka.scanner.activities.-$$Lambda$ScannerCompatActivity$7eOTyeNqxVLFta0oCTIf_1G-0bQ.onData(Unknown Source:2)
                                 	at com.enioka.scanner.api.proxies.ScannerDataCallbackProxy.lambda$onData$0$ScannerDataCallbackProxy(ScannerDataCallbackProxy.java:23)
                                 	at com.enioka.scanner.api.proxies.-$$Lambda$ScannerDataCallbackProxy$Tqa-RHhnwqg8-BwX6OTYsBnTzSQ.run(Unknown Source:6)
                                 	at android.os.Handler.handleCallback(Handler.java:938)
                                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                                 	at android.os.Looper.loop(Looper.java:246)
                                 	at android.app.ActivityThread.main(ActivityThread.java:8645)
                                 	at java.lang.reflect.Method.invoke(Native Method)
                                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
                                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
AudioTrack                    D  stop(156): called with 4992 frames delivered
```

**Comment by abelatar** [comment]
Hello @marcanpilami 
Suite à la mise à jour vers la version 2.3.7, un nouveau problème est apparu. Après un certain nombre de scans, il y a un signal d'erreur qui provoque l'arrêt de l'application :
15:59:57.894 libc                          A  Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x72f94b4004 in tid 21752 (CameraBackgroun), pid 21479 (geodis.mobiprep)


```

15:59:57.077 BufferQueueProducer           E  [ImageReader-640x480f23m18-21479-74] queueBuffer: BufferQueue(0x73067fd180) has been abandoned
15:59:57.115                               E  [ImageReader-640x480f23m18-21479-74] queueBuffer: BufferQueue(0x73067fd180) has been abandoned
15:59:57.140                               E  [ImageReader-640x480f23m18-21479-74] queueBuffer: BufferQueue(0x73067fd180) has been abandoned
15:59:57.174                               E  [ImageReader-640x480f23m18-21479-74] queueBuffer: BufferQueue(0x73067fd180) has been abandoned
15:59:57.206                               E  [ImageReader-640x480f23m18-21479-74] queueBuffer: BufferQueue(0x73067fd180) has been abandoned
15:59:57.241                               E  [ImageReader-640x480f23m18-21479-74] queueBuffer: BufferQueue(0x73067fd180) has been abandoned
15:59:57.276                               E  [ImageReader-640x480f23m18-21479-74] queueBuffer: BufferQueue(0x73067fd180) has been abandoned
15:59:57.280 CameraManagerGlobal           I  Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_IDLE for client com.geodis.mobiprep API Level 2
15:59:57.491 BARCODE                       D  Configuration request sent
15:59:57.492                               D  Preview analysis loop start method done
15:59:57.492 geodis.mobipre                W  Long monitor contention with owner main (21479) at void android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSessionInternal(android.hardware.camera2.params.InputConfiguration, java.util.List, android.hardware.camera2.CameraCaptureSession$StateCallback, java.util.concurrent.Executor, int, android.hardware.camera2.CaptureRequest)(CameraDeviceImpl.java:643) waiters=0 in void android.hardware.camera2.impl.CameraDeviceImpl$4.run() for 426ms
15:59:57.492                               W  Long monitor contention with owner main (21479) at void android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSessionInternal(android.hardware.camera2.params.InputConfiguration, java.util.List, android.hardware.camera2.CameraCaptureSession$StateCallback, java.util.concurrent.Executor, int, android.hardware.camera2.CaptureRequest)(CameraDeviceImpl.java:643) waiters=1 in void android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.onResultReceived(android.hardware.camera2.impl.CameraMetadataNative, android.hardware.camera2.impl.CaptureResultExtras, android.hardware.camera2.impl.PhysicalCaptureResultInfo[]) for 411ms
15:59:57.493 BARCODE                       I  Capture session is now configured and will start the capture request loop 245537853
15:59:57.495                               D  Using metering zone (310,310) (410,410)
15:59:57.496                               D  Setting AF mode to 4
15:59:57.503                               I  Camera repeating capture request was set up 245537853
15:59:57.503                               D  Capture session has nothing to process 245537853
15:59:57.504                               D  Capture session is getting active 245537853
15:59:57.516                               I  Capture session has closed 40940367
15:59:57.517                               D  Capture session has nothing to process 245537853
15:59:57.816 CameraManagerGlobal           I  Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_ACTIVE for client com.geodis.mobiprep API Level 2
15:59:57.855 BARCODE                       I  Discarding old buffer of length 307200 (requested 518400) 1
15:59:57.855                               D  Creating new buffer (MB) 0 count is 2
15:59:57.857                               I  Discarding old cropped buffer of length 38115 (requested 64047)
15:59:57.857                               I  Discarding old cropped buffer of length 38115 (requested 64047)
15:59:57.858                               D  Creating new cropped buffer (MB) 0
15:59:57.886                               D  barcode read: JVGTS5437650876115112
15:59:57.887 CamBarcodeScanVScanner        V  handleScanResult JVGTS5437650876115112 - CODE128
15:59:57.888 ScannerActivity               D  Received barcode from scanner: JVGTS5437650876115112 - CODE128
15:59:57.888 ParcelLoadingActivity         I  onData handled in ParcelLoadingActivity
15:59:57.888 BARCODE                       I  Stopping capture session
15:59:57.890 geodis.mobipre                W  0xebadde09 skipped times: 0
15:59:57.891 BufferQueueProducer           E  [ImageReader-720x720f23m18-21479-75] dequeueBuffer: BufferQueue has been abandoned
15:59:57.894 libc                          A  Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x72f94b4004 in tid 21752 (CameraBackgroun), pid 21479 (geodis.mobiprep)
15:59:57.928 BufferQueueProducer           E  [ImageReader-720x720f23m18-21479-75] queueBuffer: BufferQueue(0x72ecd958c0) has been abandoned
15:59:57.951                               E  [ImageReader-720x720f23m18-21479-75] queueBuffer: BufferQueue(0x72ecd958c0) has been abandoned
15:59:57.964 BARCODE                       I  Initializing or reinitializing preview analysis loop
15:59:57.966                               D  Capture session creation begins
15:59:57.984 BufferQueueProducer           E  [ImageReader-720x720f23m18-21479-75] queueBuffer: BufferQueue(0x72ecd958c0) has been abandoned
15:59:58.022                               E  [ImageReader-720x720f23m18-21479-75] queueBuffer: BufferQueue(0x72ecd958c0) has been abandoned
15:59:58.041 AudioTrack                    D  stop(45): called with 4992 frames delivered
15:59:58.043 BufferQueueProducer           E  [ImageReader-720x720f23m18-21479-75] queueBuffer: BufferQueue(0x72ecd958c0) has been abandoned
15:59:58.076                               E  [ImageReader-720x720f23m18-21479-75] queueBuffer: BufferQueue(0x72ecd958c0) has been abandoned
15:59:58.126                               E  [ImageReader-720x720f23m18-21479-75] queueBuffer: BufferQueue(0x72ecd958c0) has been abandoned
15:59:58.136 CameraManagerGlobal           I  Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_IDLE for client com.geodis.mobiprep API Level 2
15:59:58.357 BARCODE                       D  Configuration request sent
15:59:58.357                               D  Preview analysis loop start method done
15:59:58.374 ViewRootImpl@...ingActivity]  D  Relayout returned: old=(0,0,720,1280) new=(0,0,720,1280) req=(720,1280)0 dur=13 res=0x1 s={true 494112829440} ch=false
15:59:58.403 ViewRootImpl@eaf356b[Toast]   D  setView = android.widget.LinearLayout@ea288c8 TM=true MM=false
15:59:58.439                               D  Relayout returned: old=(0,48,720,1280) new=(63,976,656,1152) req=(593,176)0 dur=20 res=0x7 s={true 494114295808} ch=true
15:59:58.440 OpenGLRenderer                D  createReliableSurface : 0x736c21dd80, 0x730b81d000
15:59:58.444 mali_winsys                   D  EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
15:59:58.467 ViewRootImpl@...ingActivity]  D  Relayout returned: old=(0,0,720,1280) new=(0,0,720,1280) req=(720,1280)0 dur=9 res=0x1 s={true 494112829440} ch=false
15:59:58.480 ViewRootImpl@eaf356b[Toast]   D  MSG_RESIZED_REPORT: frame=(63,976,656,1152) ci=(0,0,0,0) vi=(0,0,593,176) or=1
15:59:59.785 ScannerActivity               I  Scanner activity is being paused 261072333
15:59:59.785 ZebraDwProvider               D  Sending intent to scanner to disable the trigger
```
