### ISSUE TITLE
Crash DataWedge TC27

### ISSUE THREAD

**Issue by mgu78** [enioka-Haute-Couture/enioka_scan#169]
le boutons de scan ne répondent plus en cours d'utilisation d'app utilisant Eniokascan. 
En activant le logcat sur la machine voici les erreurs que l'on obtient:
```
04-02 17:53:53.476  4286  4627 D BroadcastHelper: Broadcast intent finished com.symbol.datawedge.scanner_status
04-02 17:53:53.476  4286  4627 D BroadcastHelper: Sending broadcast intent com.symbol.datawedge.api.NOTIFICATION_ACTION
04-02 17:53:53.476  4286  4627 D DWHelper: getHelper
04-02 17:53:53.477  4286 27613 D DWScanner: DWScanner : user: 0: INTERNAL_IMAGER: New Scanner status SCAN_STATUS_SCANNING
04-02 17:53:53.478  4931  5097 D Avrcp_ext: AudioManager Player in started state: com.symbol.scanning.scanningframework
04-02 17:53:53.478  4931  5097 D Avrcp_ext: AudioManager Active Player: com.symbol.scanning.scanningframework
04-02 17:53:53.478  4931  5097 D Avrcp_ext: AudioManager Player: AudioPlaybackConfiguration piid:143 deviceId:3 type:OpenSL ES AudioPlayer (Buffer Queue) u/pid:10086/3974 state:stopped attr:AudioAttributes: usage=USAGE_NOTIFICATION content=CONTENT_TYPE_UNKNOWN flags=0x0 tags= bundle=null sessionId:121
04-02 17:53:53.478  4931  5097 D Avrcp_ext: AudioManager isPlaying: true, mAudioPlaybackIsActive = false
04-02 17:53:53.478  4931  5097 V Avrcp_ext: AvrcpMessageHandler: received message=38
04-02 17:53:53.478  4931  5097 D Avrcp_ext: MSG_UPDATE_CURRENT_MEDIA_STATE
04-02 17:53:53.478  4286  4627 D BroadcastHelper: Broadcast intent finished com.symbol.datawedge.api.NOTIFICATION_ACTION
04-02 17:53:53.479  1340  6152 E ActivityManager: Sending non-protected broadcast com.symbol.datawedge.api.NOTIFICATION_ACTION from system 2706:com.zebra.zvahelper/u0a98 pkg com.zebra.zvahelper
04-02 17:53:53.479  1340  6152 E ActivityManager: java.lang.Throwable
04-02 17:53:53.479  1340  6152 E ActivityManager: 	at com.android.server.am.ActivityManagerService.checkBroadcastFromSystem(ActivityManagerService.java:13753)
04-02 17:53:53.479  1340  6152 E ActivityManager: 	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:14396)
04-02 17:53:53.479  1340  6152 E ActivityManager: 	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:13771)
04-02 17:53:53.479  1340  6152 E ActivityManager: 	at com.android.server.am.ActivityManagerService.broadcastIntentWithFeature(ActivityManagerService.java:14665)
04-02 17:53:53.479  1340  6152 E ActivityManager: 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2296)
04-02 17:53:53.479  1340  6152 E ActivityManager: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2665)
04-02 17:53:53.479  1340  6152 E ActivityManager: 	at android.os.Binder.execTransactInternal(Binder.java:1280)
04-02 17:53:53.479  1340  6152 E ActivityManager: 	at android.os.Binder.execTransact(Binder.java:1244)
04-02 17:53:53.479  4931  5097 V Avrcp_ext: updateCurrentMediaState: mMediaController: null
04-02 17:53:53.479  4931  5097 W Avrcp_ext: isMusicActive: false getBluetoothPlayState: 2 A2dp State: 11 mAudioPlaybackIsActive: true
04-02 17:53:53.479  4931  5097 W Avrcp_ext: updateCurrentMediaState: isPlaying = false
04-02 17:53:53.479  4931  5097 V Avrcp_ext: Media update: id -1➡-1? [MediaAttributes: none] : [MediaAttributes: none]
04-02 17:53:53.479  4931  5097 D Avrcp_ext: isPackageNameValid: browsedPackage = isValid = false
04-02 17:53:53.479  4931  5097 W Avrcp_ext: updateCurrentMediaState: isInactivePlayer = true
04-02 17:53:53.479  4931  5097 V Avrcp_ext: updatePlaybackState, state: PlaybackState {state=2, position=-1, buffered position=0, speed=0.0, updated=23362160, actions=0, custom actions=[], active item id=-1, error=null} device: null
04-02 17:53:53.479  4931  5097 V Avrcp_ext: Device: no name: 
04-02 17:53:53.479  4931  5097 V Avrcp_ext: Device: no name: 
04-02 17:53:53.479  4931  5097 V Avrcp_ext: Device: no name: 
04-02 17:53:53.479  4931  5097 V Avrcp_ext: Device: no name: 
04-02 17:53:53.479  4931  5097 V Avrcp_ext: Device: no name: 
04-02 17:53:53.479  4931  5097 V Avrcp_ext: updatePlayerStateAndPosition, old=PlaybackState {state=2, position=-1, buffered position=0, speed=0.0, updated=22969863, actions=0, custom actions=[], active item id=-1, error=null}, state=PlaybackState {state=2, position=-1, buffered position=0, speed=0.0, updated=23362160, actions=0, custom actions=[], active item id=-1, error=null}
04-02 17:53:53.479  4931  5097 V Avrcp_ext: old state = PlaybackState {state=2, position=-1, buffered position=0, speed=0.0, updated=22969863, actions=0, custom actions=[], active item id=-1, error=null}, new state= PlaybackState {state=2, position=-1, buffered position=0, speed=0.0, updated=23362160, actions=0, custom actions=[], active item id=-1, error=null}
04-02 17:53:53.479  4931  5097 D HeadsetService: getHeadsetService(): returning com.android.bluetooth.hfp.HeadsetService@a3d1f48
04-02 17:53:53.479  1340  6152 E ActivityManager: Sending non-protected broadcast com.symbol.datawedge.api.NOTIFICATION_ACTION from system 2706:com.zebra.zvahelper/u0a98 pkg com.zebra.zvahelper
04-02 17:53:53.479  1340  6152 E ActivityManager: java.lang.Throwable
04-02 17:53:53.479  1340  6152 E ActivityManager: 	at com.android.server.am.ActivityManagerService.checkBroadcastFromSystem(ActivityManagerService.java:13753)
04-02 17:53:53.479  1340  6152 E ActivityManager: 	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:14491)
04-02 17:53:53.479  1340  6152 E ActivityManager: 	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:13771)
04-02 17:53:53.479  1340  6152 E ActivityManager: 	at com.android.server.am.ActivityManagerService.broadcastIntentWithFeature(ActivityManagerService.java:14665)
04-02 17:53:53.479  1340  6152 E ActivityManager: 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2296)
04-02 17:53:53.479  1340  6152 E ActivityManager: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2665)
04-02 17:53:53.479  1340  6152 E ActivityManager: 	at android.os.Binder.execTransactInternal(Binder.java:1280)
04-02 17:53:53.479  1340  6152 E ActivityManager: 	at android.os.Binder.execTransact(Binder.java:1244)
```

**Comment by fmanoir** [comment]
Problème résolu.
Merci @DaSpood
