### ISSUE TITLE
Exception lors du clic sur le bouton "Accueil" pendant la numérisation

### ISSUE THREAD

**Issue by abelatar** [enioka-Haute-Couture/enioka_scan#96]
Hello @marcanpilami 

Sur un Samsung Xcover 4S Lorsque je clique sur le bouton "Accueil" pendant le processus de scan, une exception non bloquante se produit lors de la configuration de la surface. Voici la trace :
SurfaceView            D  remove() android.view.SurfaceView{53cffbf V.E...... ........ 0,0-720,1120} Surface(name=SurfaceView - com.geodis.mobiprep/com.geodis.mobiprep.ScanTokenActivity@53cffbf@1)/@0xa10d9d8
                       E  Exception configuring surface
                          java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.HandlerThread.quitSafely()' on a null object reference
                          	at com.enioka.scanner.camera.CameraBarcodeScanViewV2.stopBackgroundThread(CameraBarcodeScanViewV2.java:375)
                          	at com.enioka.scanner.camera.CameraBarcodeScanViewV2.closeCamera(CameraBarcodeScanViewV2.java:312)
                          	at com.enioka.scanner.camera.CameraBarcodeScanViewV2.surfaceDestroyed(CameraBarcodeScanViewV2.java:419)
                          	at android.view.SurfaceView.updateSurface(SurfaceView.java:879)
                          	at android.view.SurfaceView.onWindowVisibilityChanged(SurfaceView.java:360)
                          	at android.view.View.dispatchWindowVisibilityChanged(View.java:14782)
                          	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1597)
                          	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1597)
                          	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1597)
                          	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1597)
                          	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1597)
                          	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1597)
                          	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1597)
                          	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1597)
                          	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1597)
                          	at com.android.internal.policy.DecorView.dispatchWindowVisibilityChanged(DecorView.java:3626)
                          	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2562)
                          	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2200)
                          	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8999)
                          	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:996)
                          	at android.view.Choreographer.doCallbacks(Choreographer.java:794)
                          	at android.view.Choreographer.doFrame(Choreographer.java:729)
                          	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:981)
                          	at android.os.Handler.handleCallback(Handler.java:883)
                          	at android.os.Handler.dispatchMessage(Handler.java:100)
                          	at android.os.Looper.loop(Looper.java:237)
                          	at android.app.ActivityThread.main(ActivityThread.java:7860)
                          	at java.lang.reflect.Method.invoke(Native Method)
                          	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                          	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
libEGL                 W  EGLNativeWindowType 0x7455d58150 disconnect failed
ViewRootI...Activity]  D  Relayout returned: old=(0,0,720,1280) new=(0,0,720,1280) req=(720,1280)8 dur=12 res=0x5 s={false 0} ch=true
                       D  stopped(true) old=false
SurfaceView            D  windowStopped(true) false android.view.SurfaceView{53cffbf V.E...... ........ 0,0-720,1120} of ViewRootImpl@f53e1de[ScanTokenActivity]
ScannerActivity        I  Scanner activity is being stopped
SurfaceView            D  onWindowVisibilityChanged(4) false android.view.SurfaceView{53cffbf V.E...... ........ 0,0-720,1120} of ViewRootImpl@f53e1de[ScanTokenActivity]
ViewRootI...Activity]  D  Relayout returned: old=(0,0,720,1280) new=(0,0,720,1280) req=(720,1280)4 dur=11 res=0x1 s={false 0} ch=false
                       D  stopped(false) old=true
SurfaceView            D  windowStopped(false) false android.view.SurfaceView{53cffbf V.E...... ........ 0,0-720,1120} of ViewRootImpl@f53e1de[ScanTokenActivity]
ScannerActivity        D  Scanner activity is starting
ViewRootI...Activity]  D  stopped(false) old=false
ScannerActivity        I  Resuming scanner activity in camera mode
                       I  Giving up on laser, going to camera
MobiprepActivity       I  Wifi is enabled
SurfaceView            D  onWindowVisibilityChanged(0) true android.view.SurfaceView{53cffbf V.E...... ........ 0,0-720,1120} of ViewRootImpl@f53e1de[ScanTokenActivity]
ViewRootI...Activity]  D  Relayout returned: old=(0,0,720,1280) new=(0,0,720,1280) req=(720,1280)0 dur=12 res=0x7 s={true 501220392960} ch=true
OpenGLRenderer         D  createReliableSurface : 0x7548c09c00, 0x74b3104000
SurfaceView            D  surfaceCreated 1 #8 android.view.SurfaceView{53cffbf V.E...... ........ 0,0-720,1120}
mali_winsys            D  EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
BARCODE                D  INFO_SUPPORTED_HARDWARE_LEVEL LIMITED
                       I  Camera supports flash: true
                       I  Using memory limit (MB): 192
                       I  Looking for the ideal preview resolution. View ratio is 1.5555556. (view is 1120*720)
                       D  	supports preview resolution 4608*3456 - 1.3333334
                       D  	supports preview resolution 4608*2592 - 1.7777778
                       D  	supports preview resolution 3840*2160 - 1.7777778
                       D  	supports preview resolution 3456*3456 - 1.0
                       D  	supports preview resolution 2576*1932 - 1.3333334
                       D  	supports preview resolution 2560*1440 - 1.7777778
                       D  	supports preview resolution 1920*1080 - 1.7777778
                       D  	supports preview resolution 1440*1080 - 1.3333334
                       D  	supports preview resolution 1280*720 - 1.7777778
                       D  	supports preview resolution 1152*864 - 1.3333334
                       D  	supports preview resolution 1088*1088 - 1.0
                       D  	supports preview resolution 1056*704 - 1.5
                       D  	supports preview resolution 1024*768 - 1.3333334
                       D  	supports preview resolution 960*720 - 1.3333334
                       D  	supports preview resolution 880*720 - 1.2222222
                       D  	supports preview resolution 800*450 - 1.7777778
                       D  	supports preview resolution 720*720 - 1.0
                       D  	supports preview resolution 720*480 - 1.5
                       D  	supports preview resolution 640*480 - 1.3333334
                       D  	supports preview resolution 480*320 - 1.5
                       D  	supports preview resolution 352*288 - 1.2222222
                       D  	supports preview resolution 320*240 - 1.3333334
                       D  	supports preview resolution 256*144 - 1.7777778
                       D  	supports preview resolution 176*144 - 1.2222222
                       D  	supports preview resolution 4608*3456 - 1.3333334
                       D  	supports preview resolution 4608*2592 - 1.7777778
                       D  	supports preview resolution 3840*2160 - 1.7777778
                       D  	supports preview resolution 3456*3456 - 1.0
                       D  	supports preview resolution 2576*1932 - 1.3333334
                       D  	supports preview resolution 2560*1440 - 1.7777778
                       D  	supports preview resolution 1920*1080 - 1.7777778
                       D  	supports preview resolution 1440*1080 - 1.3333334
                       D  	supports preview resolution 1280*720 - 1.7777778
                       D  	supports preview resolution 1152*864 - 1.3333334
                       D  	supports preview resolution 1088*1088 - 1.0
                       D  	supports preview resolution 1056*704 - 1.5
                       D  	supports preview resolution 1024*768 - 1.3333334
                       D  	supports preview resolution 960*720 - 1.3333334
                       D  	supports preview resolution 880*720 - 1.2222222
                       D  	supports preview resolution 800*450 - 1.7777778
                       D  	supports preview resolution 720*720 - 1.0
                       D  	supports preview resolution 720*480 - 1.5
                       D  	supports preview resolution 640*480 - 1.3333334
                       D  	supports preview resolution 480*320 - 1.5
                       D  	supports preview resolution 352*288 - 1.2222222
                       D  	supports preview resolution 320*240 - 1.3333334
                       D  	supports preview resolution 256*144 - 1.7777778
                       D  	supports preview resolution 176*144 - 1.2222222
                       D  	supports preview resolution 4608*3456 - 1.3333334
                       D  	supports preview resolution 4608*2592 - 1.7777778
                       D  	supports preview resolution 3840*2160 - 1.7777778
                       D  	supports preview resolution 3456*3456 - 1.0
                       D  	supports preview resolution 2576*1932 - 1.3333334
                       D  	supports preview resolution 2560*1440 - 1.7777778
                       D  	supports preview resolution 1920*1080 - 1.7777778
                       D  	supports preview resolution 1440*1080 - 1.3333334
                       D  	supports preview resolution 1280*720 - 1.7777778
                       D  	supports preview resolution 1152*864 - 1.3333334
                       D  	supports preview resolution 1088*1088 - 1.0
                       D  	supports preview resolution 1056*704 - 1.5
                       D  	supports preview resolution 1024*768 - 1.3333334
                       D  	supports preview resolution 960*720 - 1.3333334
                       D  	supports preview resolution 880*720 - 1.2222222
                       D  	supports preview resolution 800*450 - 1.7777778
                       D  	supports preview resolution 720*720 - 1.0
                       D  	supports preview resolution 720*480 - 1.5
                       D  	supports preview resolution 640*480 - 1.3333334
                       D  	supports preview resolution 480*320 - 1.5
                       D  	supports preview resolution 352*288 - 1.2222222
                       D  	supports preview resolution 320*240 - 1.3333334
                       D  	supports preview resolution 256*144 - 1.7777778
                       D  	supports preview resolution 176*144 - 1.2222222
                       V  Allowed preview sizes (acceptable ratio): 
                       V  	256*144 - 1.7777778
chatty                 I  uid=10343(com.geodis.mobiprep) identical 4 lines
BARCODE                V  	256*144 - 1.7777778
                       V  	320*240 - 1.3333334
chatty                 I  uid=10343(com.geodis.mobiprep) identical 4 lines
BARCODE                V  	320*240 - 1.3333334
                       V  	480*320 - 1.5
chatty                 I  uid=10343(com.geodis.mobiprep) identical 4 lines
BARCODE                V  	480*320 - 1.5
                       V  	640*480 - 1.3333334
chatty                 I  uid=10343(com.geodis.mobiprep) identical 4 lines
BARCODE                V  	640*480 - 1.3333334
                       V  	720*480 - 1.5
chatty                 I  uid=10343(com.geodis.mobiprep) identical 4 lines
BARCODE                V  	720*480 - 1.5
                       V  	800*450 - 1.7777778
chatty                 I  uid=10343(com.geodis.mobiprep) identical 4 lines
BARCODE                V  	800*450 - 1.7777778
                       V  	960*720 - 1.3333334
chatty                 I  uid=10343(com.geodis.mobiprep) identical 4 lines
BARCODE                V  	960*720 - 1.3333334
                       V  	1056*704 - 1.5
chatty                 I  uid=10343(com.geodis.mobiprep) identical 4 lines
BARCODE                V  	1056*704 - 1.5
                       V  	1024*768 - 1.3333334
chatty                 I  uid=10343(com.geodis.mobiprep) identical 4 lines
BARCODE                V  	1024*768 - 1.3333334
                       V  	1280*720 - 1.7777778
chatty                 I  uid=10343(com.geodis.mobiprep) identical 4 lines
BARCODE                V  	1280*720 - 1.7777778
                       V  	1152*864 - 1.3333334
chatty                 I  uid=10343(com.geodis.mobiprep) identical 4 lines
BARCODE                V  	1152*864 - 1.3333334
                       V  	1440*1080 - 1.3333334
chatty                 I  uid=10343(com.geodis.mobiprep) identical 4 lines
BARCODE                V  	1440*1080 - 1.3333334
                       V  	1920*1080 - 1.7777778
chatty                 I  uid=10343(com.geodis.mobiprep) identical 4 lines
BARCODE                V  	1920*1080 - 1.7777778
                       V  	2560*1440 - 1.7777778
chatty                 I  uid=10343(com.geodis.mobiprep) identical 4 lines
BARCODE                V  	2560*1440 - 1.7777778
                       V  	2576*1932 - 1.3333334
chatty                 I  uid=10343(com.geodis.mobiprep) identical 4 lines
BARCODE                V  	2576*1932 - 1.3333334
                       V  	3840*2160 - 1.7777778
chatty                 I  uid=10343(com.geodis.mobiprep) identical 4 lines
BARCODE                V  	3840*2160 - 1.7777778
                       V  	4608*2592 - 1.7777778
chatty                 I  uid=10343(com.geodis.mobiprep) identical 4 lines
BARCODE                V  	4608*2592 - 1.7777778
                       V  	4608*3456 - 1.3333334
chatty                 I  uid=10343(com.geodis.mobiprep) identical 4 lines
BARCODE                V  	4608*3456 - 1.3333334
                       I  Loaded preferred preview resolution Point(3840, 2160)
                       I  Camera uses preview resolution: 3840*2160
                       I  Camera uses FPS range: [8, 30]
                       I  Using AF mode: CONTROL_AF_MODE_CONTINUOUS_PICTURE
                       I  Supported autofocus zones: 1
                       I  Using AB mode: CONTROL_AE_ANTIBANDING_MODE_AUTO
CameraManagerGlobal    I  postSingleTorchUpdate device: camera id 0 status 1
                       I  postSingleTorchUpdate device: camera id 0 status 0
                       I  postSingleTorchUpdate device: camera id 0 status 0
                       I  postSingleTorchUpdate device: camera id 0 status 0
                       I  Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_OPEN for client com.geodis.mobiprep API Level 2
BARCODE                I  Setting targeting rect at Rect(72, 315 - 648, 435)
                       I  Targeting overlay added
SurfaceView            D  surfaceChanged (3840,2160) 1 #8 android.view.SurfaceView{53cffbf V.E...... ........ 0,0-720,1120}
BARCODE                I  surface changed
                       I  Initializing or reinitializing preview analysis loop
                       D  Capture session creation begins
                       D  Trying to start preview after camera shutdown - ignored.
                       D  Preview analysis loop start method done
ScanTokenActivity      D  Status changed: CONNECTED --- Scanner connecté
ViewRootI...Activity]  D  MSG_WINDOW_FOCUS_CHANGED 1 1
InputMethodManager     D  prepareNavigationBarInfo() DecorView@bf9f1d7[ScanTokenActivity]
                       D  getNavigationBarColor() -855310
                       D  prepareNavigationBarInfo() DecorView@bf9f1d7[ScanTokenActivity]
                       D  getNavigationBarColor() -855310
                       V  Starting input: tba=com.geodis.mobiprep ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
                       D  startInputInner - Id : 0
                       I  startInputInner - mService.startInputOrWindowGainedFocus
CameraManagerGlobal    I  onTorchModeChanged
BARCODE                D  Torch status has changed to: false
CameraManagerGlobal    I  onTorchModeUnavailable
chatty                 I  uid=10343(com.geodis.mobiprep) identical 1 line
CameraManagerGlobal    I  onTorchModeUnavailable
BARCODE                I  Left: 0 - Top : 315 - Right: 720 - bottom: 435
                       I  target was laid out
ScannerActivity        I  Scanner activity is being paused
CameraManagerGlobal    I  postSingleTorchUpdate device: camera id 0 status 1
                       I  postSingleTorchUpdate device: camera id 0 status 1
ViewRootI...Activity]  D  MSG_WINDOW_FOCUS_CHANGED 0 1
CameraManagerGlobal    I  postSingleTorchUpdate device: camera id 0 status 1
InputMethodManager     D  prepareNavigationBarInfo() DecorView@bf9f1d7[ScanTokenActivity]
                       D  getNavigationBarColor() -855310
CameraManagerGlobal    I  onTorchModeChanged
                       I  Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_CLOSED for client com.geodis.mobiprep API Level 2
BARCODE                D  Torch status has changed to: false
CameraManagerGlobal    I  onTorchModeChanged
BARCODE                D  Torch status has changed to: false
CameraManagerGlobal    I  onTorchModeChanged
BARCODE                D  Torch status has changed to: false
InputTransport         D  Input channel destroyed: 'ClientS', fd=71
SurfaceView            D  onWindowVisibilityChanged(8) false android.view.SurfaceView{53cffbf V.E...... ........ 0,0-720,1120} of ViewRootImpl@f53e1de[ScanTokenActivity]
                       D  surfaceDestroyed callback.size 1 #2 android.view.SurfaceView{53cffbf V.E...... ........ 0,0-720,1120}
BARCODE                I  surface destroyed
SurfaceView            D  remove() android.view.SurfaceView{53cffbf V.E...... ........ 0,0-720,1120} Surface(name=SurfaceView - com.geodis.mobiprep/com.geodis.mobiprep.ScanTokenActivity@53cffbf@2)/@0xfda6908
                       E  Exception configuring surface
                          java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.HandlerThread.quitSafely()' on a null object reference
                          	at com.enioka.scanner.camera.CameraBarcodeScanViewV2.stopBackgroundThread(CameraBarcodeScanViewV2.java:375)
                          	at com.enioka.scanner.camera.CameraBarcodeScanViewV2.closeCamera(CameraBarcodeScanViewV2.java:312)
                          	at com.enioka.scanner.camera.CameraBarcodeScanViewV2.surfaceDestroyed(CameraBarcodeScanViewV2.java:419)
                          	at android.view.SurfaceView.updateSurface(SurfaceView.java:879)
                          	at android.view.SurfaceView.onWindowVisibilityChanged(SurfaceView.java:360)
                          	at android.view.View.dispatchWindowVisibilityChanged(View.java:14782)
                          	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1597)
                          	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1597)
                          	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1597)
                          	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1597)
                          	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1597)
                          	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1597)
                          	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1597)
                          	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1597)
                          	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1597)
                          	at com.android.internal.policy.DecorView.dispatchWindowVisibilityChanged(DecorView.java:3626)
                          	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2562)
                          	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2200)
                          	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8999)
                          	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:996)
                          	at android.view.Choreographer.doCallbacks(Choreographer.java:794)
                          	at android.view.Choreographer.doFrame(Choreographer.java:729)
                          	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:981)
                          	at android.os.Handler.handleCallback(Handler.java:883)
                          	at android.os.Handler.dispatchMessage(Handler.java:100)
                          	at android.os.Looper.loop(Looper.java:237)
                          	at android.app.ActivityThread.main(ActivityThread.java:7860)
                          	at java.lang.reflect.Method.invoke(Native Method)
                          	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                          	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)

**Comment by marcanpilami** [comment]
Corrigé avec #95
